version: "3.9"
services:
  spring-app:
    build: .
    ports:
      - 8080:8080
    environment:
      VETAPP_DB_PASS: 1234
      VETAPP_DB_URL: jdbc:postgresql://postgres:5435/
      VETAPP_DB_NAME: VetApp
      VETAPP_DB_USER: VetApp

    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: VetApp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: VetApp


